"""
generate_nifty500.py
====================
Generates a comprehensive NIFTY 500 company directory for the valuation module.
This includes company name, NSE symbol, sector, and industry.

Run this file once to generate data/nifty500_companies.json
"""
import json
import os

# NIFTY 500 constituents — comprehensive list of top Indian companies
# Source: NSE India NIFTY 500 index constituents (as of April 2026)
# Organized by sector for maintainability

COMPANIES = [
    # ── Information Technology ────────────────────────────────────────────────
    {"symbol": "TCS",          "name": "Tata Consultancy Services Ltd",     "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "INFY",         "name": "Infosys Ltd",                       "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "WIPRO",        "name": "Wipro Ltd",                         "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "HCLTECH",      "name": "HCL Technologies Ltd",              "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "TECHM",        "name": "Tech Mahindra Ltd",                 "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "LTIM",         "name": "LTIMindtree Ltd",                   "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "PERSISTENT",   "name": "Persistent Systems Ltd",            "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "COFORGE",      "name": "Coforge Ltd",                       "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "MPHASIS",      "name": "MphasiS Ltd",                       "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "LTTS",         "name": "L&T Technology Services Ltd",       "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "CYIENT",       "name": "Cyient Ltd",                        "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "ZENSAR",       "name": "Zensar Technologies Ltd",           "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "BIRLASOFT",    "name": "Birlasoft Ltd",                     "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "TATAELXSI",    "name": "Tata Elxsi Ltd",                    "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "KPITTECH",     "name": "KPIT Technologies Ltd",             "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "HAPPSTMNDS",   "name": "Happiest Minds Technologies Ltd",   "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "SONATA",       "name": "Sonata Software Ltd",               "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "MASTEK",       "name": "Mastek Ltd",                        "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "ROUTE",        "name": "Route Mobile Ltd",                  "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "NEWGEN",       "name": "Newgen Software Technologies Ltd",  "sector": "Information Technology", "industry": "IT Services"},

    # ── Banking ───────────────────────────────────────────────────────────────
    {"symbol": "HDFCBANK",     "name": "HDFC Bank Ltd",                     "sector": "Banking", "industry": "Private Bank"},
    {"symbol": "ICICIBANK",    "name": "ICICI Bank Ltd",                    "sector": "Banking", "industry": "Private Bank"},
    {"symbol": "KOTAKBANK",    "name": "Kotak Mahindra Bank Ltd",           "sector": "Banking", "industry": "Private Bank"},
    {"symbol": "AXISBANK",     "name": "Axis Bank Ltd",                     "sector": "Banking", "industry": "Private Bank"},
    {"symbol": "SBIN",         "name": "State Bank Of India",               "sector": "Banking", "industry": "Public Bank"},
    {"symbol": "INDUSINDBK",   "name": "IndusInd Bank Ltd",                 "sector": "Banking", "industry": "Private Bank"},
    {"symbol": "BANKBARODA",   "name": "Bank of Baroda",                    "sector": "Banking", "industry": "Public Bank"},
    {"symbol": "PNB",          "name": "Punjab National Bank",              "sector": "Banking", "industry": "Public Bank"},
    {"symbol": "CANBK",        "name": "Canara Bank",                       "sector": "Banking", "industry": "Public Bank"},
    {"symbol": "UNIONBANK",    "name": "Union Bank of India",               "sector": "Banking", "industry": "Public Bank"},
    {"symbol": "IDFCFIRSTB",   "name": "IDFC First Bank Ltd",               "sector": "Banking", "industry": "Private Bank"},
    {"symbol": "FEDERALBNK",   "name": "Federal Bank Ltd",                  "sector": "Banking", "industry": "Private Bank"},
    {"symbol": "BANDHANBNK",   "name": "Bandhan Bank Ltd",                  "sector": "Banking", "industry": "Private Bank"},
    {"symbol": "RBLBANK",      "name": "RBL Bank Ltd",                      "sector": "Banking", "industry": "Private Bank"},
    {"symbol": "AUBANK",       "name": "AU Small Finance Bank Ltd",         "sector": "Banking", "industry": "Small Finance Bank"},
    {"symbol": "IOB",          "name": "Indian Overseas Bank",              "sector": "Banking", "industry": "Public Bank"},
    {"symbol": "INDIANB",      "name": "Indian Bank",                       "sector": "Banking", "industry": "Public Bank"},
    {"symbol": "MAHABANK",     "name": "Bank of Maharashtra",               "sector": "Banking", "industry": "Public Bank"},
    {"symbol": "CENTRALBK",    "name": "Central Bank of India",             "sector": "Banking", "industry": "Public Bank"},
    {"symbol": "UCOBANK",      "name": "UCO Bank",                          "sector": "Banking", "industry": "Public Bank"},
    {"symbol": "CUB",          "name": "City Union Bank Ltd",               "sector": "Banking", "industry": "Private Bank"},
    {"symbol": "KARURVYSYA",   "name": "Karur Vysya Bank Ltd",              "sector": "Banking", "industry": "Private Bank"},
    {"symbol": "EQUITASBNK",   "name": "Equitas Small Finance Bank Ltd",    "sector": "Banking", "industry": "Small Finance Bank"},
    {"symbol": "UJJIVANSFB",   "name": "Ujjivan Small Finance Bank Ltd",    "sector": "Banking", "industry": "Small Finance Bank"},
    {"symbol": "YESBANK",      "name": "Yes Bank Ltd",                      "sector": "Banking", "industry": "Private Bank"},

    # ── Financial Services (NBFC, Insurance, AMC) ─────────────────────────────
    {"symbol": "BAJFINANCE",   "name": "Bajaj Finance Ltd",                 "sector": "Financial Services", "industry": "NBFC"},
    {"symbol": "BAJAJFINSV",   "name": "Bajaj Finserv Ltd",                 "sector": "Financial Services", "industry": "NBFC"},
    {"symbol": "SBILIFE",      "name": "SBI Life Insurance Company Ltd",    "sector": "Financial Services", "industry": "Insurance"},
    {"symbol": "HDFCLIFE",     "name": "HDFC Life Insurance Company Ltd",   "sector": "Financial Services", "industry": "Insurance"},
    {"symbol": "ICICIPRULI",   "name": "ICICI Prudential Life Insurance",   "sector": "Financial Services", "industry": "Insurance"},
    {"symbol": "ICICIGI",      "name": "ICICI Lombard General Insurance",   "sector": "Financial Services", "industry": "Insurance"},
    {"symbol": "SBICARD",      "name": "SBI Cards & Payment Services Ltd",  "sector": "Financial Services", "industry": "Consumer Finance"},
    {"symbol": "CHOLAFIN",     "name": "Cholamandalam Investment & Finance", "sector": "Financial Services", "industry": "NBFC"},
    {"symbol": "SHRIRAMFIN",   "name": "Shriram Finance Ltd",               "sector": "Financial Services", "industry": "NBFC"},
    {"symbol": "MUTHOOTFIN",   "name": "Muthoot Finance Ltd",               "sector": "Financial Services", "industry": "NBFC"},
    {"symbol": "M&MFIN",       "name": "Mahindra & Mahindra Financial",     "sector": "Financial Services", "industry": "NBFC"},
    {"symbol": "MANAPPURAM",   "name": "Manappuram Finance Ltd",            "sector": "Financial Services", "industry": "NBFC"},
    {"symbol": "PEL",          "name": "Piramal Enterprises Ltd",           "sector": "Financial Services", "industry": "NBFC"},
    {"symbol": "LICHSGFIN",    "name": "LIC Housing Finance Ltd",           "sector": "Financial Services", "industry": "Housing Finance"},
    {"symbol": "CANFINHOME",   "name": "Can Fin Homes Ltd",                 "sector": "Financial Services", "industry": "Housing Finance"},
    {"symbol": "AAVAS",        "name": "Aavas Financiers Ltd",              "sector": "Financial Services", "industry": "Housing Finance"},
    {"symbol": "HDFCAMC",      "name": "HDFC Asset Management Company Ltd", "sector": "Financial Services", "industry": "AMC"},
    {"symbol": "NAM-INDIA",    "name": "Nippon Life India AMC Ltd",         "sector": "Financial Services", "industry": "AMC"},
    {"symbol": "NIACL",        "name": "New India Assurance Company Ltd",   "sector": "Financial Services", "industry": "Insurance"},
    {"symbol": "GICRE",        "name": "General Insurance Corp of India",   "sector": "Financial Services", "industry": "Insurance"},
    {"symbol": "STARHEALTH",   "name": "Star Health & Allied Insurance",    "sector": "Financial Services", "industry": "Insurance"},
    {"symbol": "POONAWALLA",   "name": "Poonawalla Fincorp Ltd",            "sector": "Financial Services", "industry": "NBFC"},
    {"symbol": "SUNDARMFIN",   "name": "Sundaram Finance Ltd",              "sector": "Financial Services", "industry": "NBFC"},
    {"symbol": "CAMS",         "name": "Computer Age Management Services",  "sector": "Financial Services", "industry": "Capital Markets"},
    {"symbol": "CDSL",         "name": "Central Depository Services Ltd",   "sector": "Financial Services", "industry": "Capital Markets"},
    {"symbol": "BSE",          "name": "BSE Ltd",                           "sector": "Financial Services", "industry": "Capital Markets"},
    {"symbol": "MCX",          "name": "Multi Commodity Exchange of India",  "sector": "Financial Services", "industry": "Capital Markets"},
    {"symbol": "ANGELONE",     "name": "Angel One Ltd",                     "sector": "Financial Services", "industry": "Capital Markets"},
    {"symbol": "JIOFIN",       "name": "Jio Financial Services Ltd",        "sector": "Financial Services", "industry": "Financial Services"},
    {"symbol": "PAYTM",        "name": "One97 Communications Ltd",          "sector": "Financial Services", "industry": "Fintech"},
    {"symbol": "PB",           "name": "Policy Bazaar (PB Fintech Ltd)",    "sector": "Financial Services", "industry": "Fintech"},

    # ── Energy & Oil ──────────────────────────────────────────────────────────
    {"symbol": "RELIANCE",     "name": "Reliance Industries Ltd",           "sector": "Energy & Retail", "industry": "Conglomerate"},
    {"symbol": "ONGC",         "name": "Oil & Natural Gas Corporation Ltd", "sector": "Energy", "industry": "Oil & Gas"},
    {"symbol": "IOC",          "name": "Indian Oil Corporation Ltd",        "sector": "Energy", "industry": "Oil & Gas"},
    {"symbol": "BPCL",         "name": "Bharat Petroleum Corporation Ltd",  "sector": "Energy", "industry": "Oil & Gas"},
    {"symbol": "HINDPETRO",    "name": "Hindustan Petroleum Corporation",   "sector": "Energy", "industry": "Oil & Gas"},
    {"symbol": "GAIL",         "name": "GAIL (India) Ltd",                  "sector": "Energy", "industry": "Oil & Gas"},
    {"symbol": "NTPC",         "name": "NTPC Ltd",                          "sector": "Energy", "industry": "Power"},
    {"symbol": "POWERGRID",    "name": "Power Grid Corporation of India",   "sector": "Energy", "industry": "Power"},
    {"symbol": "ADANIGREEN",   "name": "Adani Green Energy Ltd",            "sector": "Energy", "industry": "Renewable Energy"},
    {"symbol": "ADANIENT",     "name": "Adani Enterprises Ltd",             "sector": "Energy", "industry": "Conglomerate"},
    {"symbol": "ADANIPORTS",   "name": "Adani Ports & SEZ Ltd",             "sector": "Infrastructure", "industry": "Ports"},
    {"symbol": "ADANIPOWER",   "name": "Adani Power Ltd",                   "sector": "Energy", "industry": "Power"},
    {"symbol": "ADANITRANS",   "name": "Adani Energy Solutions Ltd",        "sector": "Energy", "industry": "Power Transmission"},
    {"symbol": "TATAPOWER",    "name": "Tata Power Company Ltd",            "sector": "Energy", "industry": "Power"},
    {"symbol": "NHPC",         "name": "NHPC Ltd",                          "sector": "Energy", "industry": "Hydropower"},
    {"symbol": "SJVN",         "name": "SJVN Ltd",                          "sector": "Energy", "industry": "Hydropower"},
    {"symbol": "IREDA",        "name": "Indian Renewable Energy Dev Agency","sector": "Energy", "industry": "Renewable Energy"},
    {"symbol": "COALINDIA",    "name": "Coal India Ltd",                    "sector": "Energy", "industry": "Mining"},
    {"symbol": "PETRONET",     "name": "Petronet LNG Ltd",                  "sector": "Energy", "industry": "Oil & Gas"},
    {"symbol": "IGL",          "name": "Indraprastha Gas Ltd",              "sector": "Energy", "industry": "Gas Distribution"},
    {"symbol": "MGL",          "name": "Mahanagar Gas Ltd",                 "sector": "Energy", "industry": "Gas Distribution"},
    {"symbol": "GUJGASLTD",    "name": "Gujarat Gas Ltd",                   "sector": "Energy", "industry": "Gas Distribution"},
    {"symbol": "TORNTPOWER",   "name": "Torrent Power Ltd",                 "sector": "Energy", "industry": "Power"},
    {"symbol": "CESC",         "name": "CESC Ltd",                          "sector": "Energy", "industry": "Power"},
    {"symbol": "JSW ENERGY",   "name": "JSW Energy Ltd",                    "sector": "Energy", "industry": "Power"},
    {"symbol": "RECLTD",       "name": "REC Ltd",                           "sector": "Energy", "industry": "Power Finance"},
    {"symbol": "PFC",          "name": "Power Finance Corporation Ltd",     "sector": "Energy", "industry": "Power Finance"},

    # ── Automobile ────────────────────────────────────────────────────────────
    {"symbol": "MARUTI",       "name": "Maruti Suzuki India Ltd",           "sector": "Automobile", "industry": "Passenger Vehicles"},
    {"symbol": "TATAMOTORS",   "name": "Tata Motors Ltd",                   "sector": "Automobile", "industry": "Commercial Vehicles"},
    {"symbol": "M&M",          "name": "Mahindra & Mahindra Ltd",           "sector": "Automobile", "industry": "Utility Vehicles"},
    {"symbol": "BAJAJ-AUTO",   "name": "Bajaj Auto Ltd",                    "sector": "Automobile", "industry": "Two-Wheelers"},
    {"symbol": "HEROMOTOCO",   "name": "Hero MotoCorp Ltd",                 "sector": "Automobile", "industry": "Two-Wheelers"},
    {"symbol": "EICHERMOT",    "name": "Eicher Motors Ltd",                 "sector": "Automobile", "industry": "Two-Wheelers"},
    {"symbol": "ASHOKLEY",     "name": "Ashok Leyland Ltd",                 "sector": "Automobile", "industry": "Commercial Vehicles"},
    {"symbol": "TVSMOTOR",     "name": "TVS Motor Company Ltd",             "sector": "Automobile", "industry": "Two-Wheelers"},
    {"symbol": "TIINDIA",      "name": "Tube Investments of India Ltd",     "sector": "Automobile", "industry": "Auto Components"},
    {"symbol": "MOTHERSON",    "name": "Motherson Sumi Wiring India Ltd",   "sector": "Automobile", "industry": "Auto Components"},
    {"symbol": "BHARATFORG",   "name": "Bharat Forge Ltd",                  "sector": "Automobile", "industry": "Auto Components"},
    {"symbol": "BALKRISIND",   "name": "Balkrishna Industries Ltd",         "sector": "Automobile", "industry": "Tyres"},
    {"symbol": "MRF",          "name": "MRF Ltd",                           "sector": "Automobile", "industry": "Tyres"},
    {"symbol": "APOLLOTYRE",   "name": "Apollo Tyres Ltd",                  "sector": "Automobile", "industry": "Tyres"},
    {"symbol": "CEATLTD",      "name": "CEAT Ltd",                          "sector": "Automobile", "industry": "Tyres"},
    {"symbol": "SOLARINDS",    "name": "Solar Industries India Ltd",        "sector": "Automobile", "industry": "Explosives"},
    {"symbol": "BOSCHLTD",     "name": "Bosch Ltd",                         "sector": "Automobile", "industry": "Auto Components"},
    {"symbol": "EXIDEIND",     "name": "Exide Industries Ltd",              "sector": "Automobile", "industry": "Auto Ancillary"},
    {"symbol": "AMARARAJA",    "name": "Amara Raja Energy & Mobility Ltd",  "sector": "Automobile", "industry": "Auto Ancillary"},
    {"symbol": "ESCORTS",      "name": "Escorts Kubota Ltd",                "sector": "Automobile", "industry": "Tractors"},
    {"symbol": "OLECTRA",      "name": "Olectra Greentech Ltd",             "sector": "Automobile", "industry": "Electric Vehicles"},
    {"symbol": "TATAMTRDVR",   "name": "Tata Motors DVR",                   "sector": "Automobile", "industry": "Commercial Vehicles"},

    # ── Pharmaceutical & Healthcare ───────────────────────────────────────────
    {"symbol": "SUNPHARMA",    "name": "Sun Pharmaceutical Industries Ltd", "sector": "Pharmaceuticals", "industry": "Pharma"},
    {"symbol": "DRREDDY",      "name": "Dr Reddys Laboratories Ltd",        "sector": "Pharmaceuticals", "industry": "Pharma"},
    {"symbol": "CIPLA",        "name": "Cipla Ltd",                         "sector": "Pharmaceuticals", "industry": "Pharma"},
    {"symbol": "DIVISLAB",     "name": "Divis Laboratories Ltd",            "sector": "Pharmaceuticals", "industry": "API"},
    {"symbol": "APOLLOHOSP",   "name": "Apollo Hospitals Enterprise Ltd",   "sector": "Healthcare", "industry": "Hospitals"},
    {"symbol": "MAXHEALTH",    "name": "Max Healthcare Institute Ltd",      "sector": "Healthcare", "industry": "Hospitals"},
    {"symbol": "FORTIS",       "name": "Fortis Healthcare Ltd",             "sector": "Healthcare", "industry": "Hospitals"},
    {"symbol": "MANKIND",      "name": "Mankind Pharma Ltd",                "sector": "Pharmaceuticals", "industry": "Pharma"},
    {"symbol": "TORNTPHARM",   "name": "Torrent Pharmaceuticals Ltd",       "sector": "Pharmaceuticals", "industry": "Pharma"},
    {"symbol": "ZYDUSLIFE",    "name": "Zydus Lifesciences Ltd",            "sector": "Pharmaceuticals", "industry": "Pharma"},
    {"symbol": "AUROPHARMA",   "name": "Aurobindo Pharma Ltd",              "sector": "Pharmaceuticals", "industry": "Pharma"},
    {"symbol": "LUPIN",        "name": "Lupin Ltd",                         "sector": "Pharmaceuticals", "industry": "Pharma"},
    {"symbol": "BIOCON",       "name": "Biocon Ltd",                        "sector": "Pharmaceuticals", "industry": "Biotech"},
    {"symbol": "ALKEM",        "name": "Alkem Laboratories Ltd",            "sector": "Pharmaceuticals", "industry": "Pharma"},
    {"symbol": "GLENMARK",     "name": "Glenmark Pharmaceuticals Ltd",      "sector": "Pharmaceuticals", "industry": "Pharma"},
    {"symbol": "IPCALAB",      "name": "IPCA Laboratories Ltd",             "sector": "Pharmaceuticals", "industry": "Pharma"},
    {"symbol": "LAURUSLABS",   "name": "Laurus Labs Ltd",                   "sector": "Pharmaceuticals", "industry": "API"},
    {"symbol": "SYNGENE",      "name": "Syngene International Ltd",         "sector": "Pharmaceuticals", "industry": "CRAMS"},
    {"symbol": "NATCOPHARM",   "name": "Natco Pharma Ltd",                  "sector": "Pharmaceuticals", "industry": "Pharma"},
    {"symbol": "ASTRAZEN",     "name": "AstraZeneca Pharma India Ltd",      "sector": "Pharmaceuticals", "industry": "MNC Pharma"},
    {"symbol": "PFIZER",       "name": "Pfizer Ltd",                        "sector": "Pharmaceuticals", "industry": "MNC Pharma"},
    {"symbol": "ABBOTINDIA",   "name": "Abbott India Ltd",                  "sector": "Pharmaceuticals", "industry": "MNC Pharma"},
    {"symbol": "METROPOLIS",   "name": "Metropolis Healthcare Ltd",         "sector": "Healthcare", "industry": "Diagnostics"},
    {"symbol": "LALPATHLAB",   "name": "Dr Lal PathLabs Ltd",               "sector": "Healthcare", "industry": "Diagnostics"},

    # ── Consumer Goods (FMCG) ─────────────────────────────────────────────────
    {"symbol": "HINDUNILVR",   "name": "Hindustan Unilever Ltd",            "sector": "FMCG", "industry": "Personal Care"},
    {"symbol": "ITC",          "name": "ITC Ltd",                           "sector": "FMCG", "industry": "Cigarettes & FMCG"},
    {"symbol": "NESTLEIND",    "name": "Nestle India Ltd",                  "sector": "FMCG", "industry": "Food Products"},
    {"symbol": "BRITANNIA",    "name": "Britannia Industries Ltd",          "sector": "FMCG", "industry": "Food Products"},
    {"symbol": "GODREJCP",     "name": "Godrej Consumer Products Ltd",      "sector": "FMCG", "industry": "Personal Care"},
    {"symbol": "MARICO",       "name": "Marico Ltd",                        "sector": "FMCG", "industry": "Personal Care"},
    {"symbol": "DABUR",        "name": "Dabur India Ltd",                   "sector": "FMCG", "industry": "Personal Care"},
    {"symbol": "COLPAL",       "name": "Colgate-Palmolive (India) Ltd",     "sector": "FMCG", "industry": "Personal Care"},
    {"symbol": "TATACONSUM",   "name": "Tata Consumer Products Ltd",        "sector": "FMCG", "industry": "Food Products"},
    {"symbol": "EMAMILTD",     "name": "Emami Ltd",                         "sector": "FMCG", "industry": "Personal Care"},
    {"symbol": "PGHH",         "name": "Procter & Gamble Hygiene & Health", "sector": "FMCG", "industry": "Personal Care"},
    {"symbol": "VBL",          "name": "Varun Beverages Ltd",               "sector": "FMCG", "industry": "Beverages"},
    {"symbol": "UBL",          "name": "United Breweries Ltd",              "sector": "FMCG", "industry": "Beverages"},
    {"symbol": "RADICO",       "name": "Radico Khaitan Ltd",                "sector": "FMCG", "industry": "Beverages"},
    {"symbol": "MCDOWELL-N",   "name": "United Spirits Ltd",                "sector": "FMCG", "industry": "Beverages"},
    {"symbol": "JUBLFOOD",     "name": "Jubilant FoodWorks Ltd",            "sector": "FMCG", "industry": "Quick Service Restaurant"},
    {"symbol": "ZOMATO",       "name": "Zomato Ltd",                        "sector": "FMCG", "industry": "Food Delivery"},
    {"symbol": "DEVYANI",      "name": "Devyani International Ltd",         "sector": "FMCG", "industry": "Quick Service Restaurant"},
    {"symbol": "BIKAJI",       "name": "Bikaji Foods International Ltd",    "sector": "FMCG", "industry": "Food Products"},
    {"symbol": "PATANJALI",    "name": "Patanjali Foods Ltd",               "sector": "FMCG", "industry": "Food Products"},
    {"symbol": "DMART",        "name": "Avenue Supermarts Ltd (DMart)",     "sector": "Retail", "industry": "Retail"},
    {"symbol": "TRENT",        "name": "Trent Ltd",                         "sector": "Retail", "industry": "Retail"},
    {"symbol": "SHOPERSTOP",   "name": "Shoppers Stop Ltd",                 "sector": "Retail", "industry": "Retail"},
    {"symbol": "TITAN",        "name": "Titan Company Ltd",                 "sector": "Consumer Goods", "industry": "Jewellery"},
    {"symbol": "PAGEIND",      "name": "Page Industries Ltd",               "sector": "Consumer Goods", "industry": "Textiles"},

    # ── Metals & Mining ───────────────────────────────────────────────────────
    {"symbol": "TATASTEEL",    "name": "Tata Steel Ltd",                    "sector": "Metals & Mining", "industry": "Steel"},
    {"symbol": "JSWSTEEL",     "name": "JSW Steel Ltd",                     "sector": "Metals & Mining", "industry": "Steel"},
    {"symbol": "HINDALCO",     "name": "Hindalco Industries Ltd",           "sector": "Metals & Mining", "industry": "Aluminium"},
    {"symbol": "VEDL",         "name": "Vedanta Ltd",                       "sector": "Metals & Mining", "industry": "Metals"},
    {"symbol": "SAIL",         "name": "Steel Authority of India Ltd",      "sector": "Metals & Mining", "industry": "Steel"},
    {"symbol": "NMDC",         "name": "NMDC Ltd",                          "sector": "Metals & Mining", "industry": "Mining"},
    {"symbol": "NATIONALUM",   "name": "National Aluminium Company Ltd",    "sector": "Metals & Mining", "industry": "Aluminium"},
    {"symbol": "JINDALSTEL",   "name": "Jindal Steel & Power Ltd",          "sector": "Metals & Mining", "industry": "Steel"},
    {"symbol": "APLAPOLLO",    "name": "APL Apollo Tubes Ltd",              "sector": "Metals & Mining", "industry": "Steel Tubes"},
    {"symbol": "HINDZINC",     "name": "Hindustan Zinc Ltd",                "sector": "Metals & Mining", "industry": "Zinc"},
    {"symbol": "RATNAMANI",    "name": "Ratnamani Metals & Tubes Ltd",      "sector": "Metals & Mining", "industry": "Steel Tubes"},
    {"symbol": "WELCORP",      "name": "Welspun Corp Ltd",                  "sector": "Metals & Mining", "industry": "Steel Pipes"},

    # ── Cement & Construction ─────────────────────────────────────────────────
    {"symbol": "ULTRACEMCO",   "name": "UltraTech Cement Ltd",              "sector": "Cement", "industry": "Cement"},
    {"symbol": "SHREECEM",     "name": "Shree Cement Ltd",                  "sector": "Cement", "industry": "Cement"},
    {"symbol": "AMBUJACEM",    "name": "Ambuja Cements Ltd",                "sector": "Cement", "industry": "Cement"},
    {"symbol": "ACC",          "name": "ACC Ltd",                           "sector": "Cement", "industry": "Cement"},
    {"symbol": "DALMIACEM",    "name": "Dalmia Bharat Ltd",                 "sector": "Cement", "industry": "Cement"},
    {"symbol": "RAMCOCEM",     "name": "The Ramco Cements Ltd",             "sector": "Cement", "industry": "Cement"},
    {"symbol": "JKCEMENT",     "name": "JK Cement Ltd",                     "sector": "Cement", "industry": "Cement"},
    {"symbol": "NUVOCO",       "name": "Nuvoco Vistas Corporation Ltd",     "sector": "Cement", "industry": "Cement"},
    {"symbol": "JKLAKSHMI",    "name": "JK Lakshmi Cement Ltd",             "sector": "Cement", "industry": "Cement"},
    {"symbol": "BIRLACEM",     "name": "Birla Corporation Ltd",             "sector": "Cement", "industry": "Cement"},
    {"symbol": "STARCEMENT",   "name": "Star Cement Ltd",                   "sector": "Cement", "industry": "Cement"},
    {"symbol": "LT",           "name": "Larsen & Toubro Ltd",               "sector": "Construction", "industry": "Infrastructure"},
    {"symbol": "LTSG",         "name": "L&T SmartWorld & Communication",    "sector": "Construction", "industry": "Infrastructure"},
    {"symbol": "GODREJPROP",   "name": "Godrej Properties Ltd",             "sector": "Real Estate", "industry": "Real Estate"},
    {"symbol": "DLF",          "name": "DLF Ltd",                           "sector": "Real Estate", "industry": "Real Estate"},
    {"symbol": "OBEROIRLTY",   "name": "Oberoi Realty Ltd",                 "sector": "Real Estate", "industry": "Real Estate"},
    {"symbol": "PRESTIGE",     "name": "Prestige Estates Projects Ltd",     "sector": "Real Estate", "industry": "Real Estate"},
    {"symbol": "BRIGADE",      "name": "Brigade Enterprises Ltd",           "sector": "Real Estate", "industry": "Real Estate"},
    {"symbol": "LODHA",        "name": "Macrotech Developers Ltd",          "sector": "Real Estate", "industry": "Real Estate"},
    {"symbol": "PHOENIXLTD",   "name": "The Phoenix Mills Ltd",             "sector": "Real Estate", "industry": "Real Estate"},

    # ── Telecom ───────────────────────────────────────────────────────────────
    {"symbol": "BHARTIARTL",   "name": "Bharti Airtel Ltd",                 "sector": "Telecom", "industry": "Telecom"},
    {"symbol": "IDEA",         "name": "Vodafone Idea Ltd",                 "sector": "Telecom", "industry": "Telecom"},
    {"symbol": "TTML",         "name": "Tata Teleservices (Maharashtra)",   "sector": "Telecom", "industry": "Telecom"},
    {"symbol": "INDUSTOWER",   "name": "Indus Towers Ltd",                  "sector": "Telecom", "industry": "Telecom Infra"},

    # ── Capital Goods & Engineering ───────────────────────────────────────────
    {"symbol": "SIEMENS",      "name": "Siemens Ltd",                       "sector": "Capital Goods", "industry": "Electrical Equipment"},
    {"symbol": "ABB",          "name": "ABB India Ltd",                     "sector": "Capital Goods", "industry": "Electrical Equipment"},
    {"symbol": "HAL",          "name": "Hindustan Aeronautics Ltd",         "sector": "Defence", "industry": "Aerospace"},
    {"symbol": "BEL",          "name": "Bharat Electronics Ltd",            "sector": "Defence", "industry": "Defence Electronics"},
    {"symbol": "BDL",          "name": "Bharat Dynamics Ltd",               "sector": "Defence", "industry": "Defence"},
    {"symbol": "MAZAGON",      "name": "Mazagon Dock Shipbuilders Ltd",     "sector": "Defence", "industry": "Shipbuilding"},
    {"symbol": "COCHINSHIP",   "name": "Cochin Shipyard Ltd",               "sector": "Defence", "industry": "Shipbuilding"},
    {"symbol": "GRSE",         "name": "Garden Reach Shipbuilders & Eng",   "sector": "Defence", "industry": "Shipbuilding"},
    {"symbol": "BHEL",         "name": "Bharat Heavy Electricals Ltd",      "sector": "Capital Goods", "industry": "Power Equipment"},
    {"symbol": "THERMAX",      "name": "Thermax Ltd",                       "sector": "Capital Goods", "industry": "Energy Equipment"},
    {"symbol": "CUMMINSIND",   "name": "Cummins India Ltd",                 "sector": "Capital Goods", "industry": "Engines"},
    {"symbol": "CGPOWER",      "name": "CG Power and Industrial Solutions", "sector": "Capital Goods", "industry": "Electrical Equipment"},
    {"symbol": "KAYNES",       "name": "Kaynes Technology India Ltd",       "sector": "Capital Goods", "industry": "Electronics Manufacturing"},
    {"symbol": "DIXON",        "name": "Dixon Technologies (India) Ltd",    "sector": "Capital Goods", "industry": "Electronics Manufacturing"},
    {"symbol": "HONAUT",       "name": "Honeywell Automation India Ltd",    "sector": "Capital Goods", "industry": "Automation"},
    {"symbol": "VOLTAS",       "name": "Voltas Ltd",                        "sector": "Capital Goods", "industry": "Air Conditioning"},
    {"symbol": "HAVELLS",      "name": "Havells India Ltd",                 "sector": "Capital Goods", "industry": "Electrical"},
    {"symbol": "POLYCAB",      "name": "Polycab India Ltd",                 "sector": "Capital Goods", "industry": "Cables"},
    {"symbol": "KEI",          "name": "KEI Industries Ltd",                "sector": "Capital Goods", "industry": "Cables"},
    {"symbol": "CROMPTON",     "name": "Crompton Greaves Consumer Elect",   "sector": "Capital Goods", "industry": "Consumer Electricals"},
    {"symbol": "BAJAJELEC",    "name": "Bajaj Electricals Ltd",             "sector": "Capital Goods", "industry": "Consumer Electricals"},
    {"symbol": "ELGIEQUIP",    "name": "Elgi Equipments Ltd",               "sector": "Capital Goods", "industry": "Compressors"},
    {"symbol": "GRINFRA",      "name": "G R Infraprojects Ltd",             "sector": "Construction", "industry": "Roads"},
    {"symbol": "IRCON",        "name": "IRCON International Ltd",           "sector": "Construction", "industry": "Railways"},
    {"symbol": "RVNL",         "name": "Rail Vikas Nigam Ltd",              "sector": "Construction", "industry": "Railways"},
    {"symbol": "NBCC",         "name": "NBCC (India) Ltd",                  "sector": "Construction", "industry": "Construction"},
    {"symbol": "NCC",          "name": "NCC Ltd",                           "sector": "Construction", "industry": "Roads"},

    # ── Chemicals ─────────────────────────────────────────────────────────────
    {"symbol": "PIDILITIND",   "name": "Pidilite Industries Ltd",           "sector": "Chemicals", "industry": "Adhesives"},
    {"symbol": "SRF",          "name": "SRF Ltd",                           "sector": "Chemicals", "industry": "Specialty Chemicals"},
    {"symbol": "PIIND",        "name": "PI Industries Ltd",                 "sector": "Chemicals", "industry": "Agrochemicals"},
    {"symbol": "ATUL",         "name": "Atul Ltd",                          "sector": "Chemicals", "industry": "Specialty Chemicals"},
    {"symbol": "DEEPAKNTR",    "name": "Deepak Nitrite Ltd",                "sector": "Chemicals", "industry": "Specialty Chemicals"},
    {"symbol": "NAVIN",        "name": "Navin Fluorine International Ltd",  "sector": "Chemicals", "industry": "Specialty Chemicals"},
    {"symbol": "CLEAN",        "name": "Clean Science & Technology Ltd",    "sector": "Chemicals", "industry": "Specialty Chemicals"},
    {"symbol": "FINEPHARMA",   "name": "Fine Organic Industries Ltd",       "sector": "Chemicals", "industry": "Specialty Chemicals"},
    {"symbol": "TATACHEM",     "name": "Tata Chemicals Ltd",                "sector": "Chemicals", "industry": "Basic Chemicals"},
    {"symbol": "UPL",          "name": "UPL Ltd",                           "sector": "Chemicals", "industry": "Agrochemicals"},
    {"symbol": "BASF",         "name": "BASF India Ltd",                    "sector": "Chemicals", "industry": "Specialty Chemicals"},
    {"symbol": "SUMICHEM",     "name": "Sumitomo Chemical India Ltd",       "sector": "Chemicals", "industry": "Agrochemicals"},
    {"symbol": "ASIANPAINT",   "name": "Asian Paints Ltd",                  "sector": "Chemicals", "industry": "Paints"},
    {"symbol": "BERGEPAINT",   "name": "Berger Paints India Ltd",           "sector": "Chemicals", "industry": "Paints"},
    {"symbol": "AKZONOBEL",    "name": "Akzo Nobel India Ltd",              "sector": "Chemicals", "industry": "Paints"},
    {"symbol": "INDIGO",       "name": "Indigo Paints Ltd",                 "sector": "Chemicals", "industry": "Paints"},
    {"symbol": "KANSAINER",    "name": "Kansai Nerolac Paints Ltd",         "sector": "Chemicals", "industry": "Paints"},

    # ── Media & Entertainment ─────────────────────────────────────────────────
    {"symbol": "ZEEL",         "name": "Zee Entertainment Enterprises Ltd", "sector": "Media", "industry": "Broadcasting"},
    {"symbol": "PVR",          "name": "PVR INOX Ltd",                      "sector": "Media", "industry": "Entertainment"},
    {"symbol": "SUNTV",        "name": "Sun TV Network Ltd",                "sector": "Media", "industry": "Broadcasting"},
    {"symbol": "NETWORK18",    "name": "Network18 Media & Investments",     "sector": "Media", "industry": "Broadcasting"},
    {"symbol": "NAZARA",       "name": "Nazara Technologies Ltd",           "sector": "Media", "industry": "Gaming"},
    {"symbol": "NYKAA",        "name": "FSN E-Commerce Ventures Ltd",       "sector": "Retail", "industry": "E-Commerce"},
    {"symbol": "CARTRADE",     "name": "CarTrade Tech Ltd",                 "sector": "Media", "industry": "Online Classifieds"},
    {"symbol": "JUSTDIAL",     "name": "Just Dial Ltd",                     "sector": "Media", "industry": "Online Services"},
    {"symbol": "INDIAMART",    "name": "IndiaMART InterMESH Ltd",           "sector": "Media", "industry": "Online B2B"},
    {"symbol": "INFOEDGE",     "name": "Info Edge (India) Ltd",             "sector": "Media", "industry": "Online Services"},

    # ── Hotels, Travel & Tourism ──────────────────────────────────────────────
    {"symbol": "TATACOMM",     "name": "Tata Communications Ltd",           "sector": "Telecom", "industry": "Telecom Services"},
    {"symbol": "INDHOTEL",     "name": "Indian Hotels Company Ltd",         "sector": "Hotels", "industry": "Hospitality"},
    {"symbol": "LEMON",        "name": "Lemon Tree Hotels Ltd",             "sector": "Hotels", "industry": "Hospitality"},
    {"symbol": "EIH",          "name": "EIH Ltd (Oberoi Hotels)",           "sector": "Hotels", "industry": "Hospitality"},
    {"symbol": "IRCTC",        "name": "Indian Railway Catering & Tourism", "sector": "Travel", "industry": "Tourism"},
    {"symbol": "MAKEMYTRIP",   "name": "MakeMyTrip Ltd",                    "sector": "Travel", "industry": "Online Travel"},
    {"symbol": "IXIGO",        "name": "Le Travenues Technology Ltd",       "sector": "Travel", "industry": "Online Travel"},

    # ── Others (Diversified, Logistics, etc.) ─────────────────────────────────
    {"symbol": "HDFCLIFE",     "name": "HDFC Life Insurance Company Ltd",   "sector": "Insurance", "industry": "Life Insurance"},
    {"symbol": "LTI",          "name": "LTI Mindtree Ltd",                  "sector": "IT", "industry": "IT Services"},
    {"symbol": "CONCOR",       "name": "Container Corporation of India",    "sector": "Logistics", "industry": "Railways Logistics"},
    {"symbol": "DELHIVERY",    "name": "Delhivery Ltd",                     "sector": "Logistics", "industry": "Express Logistics"},
    {"symbol": "VRL",          "name": "VRL Logistics Ltd",                 "sector": "Logistics", "industry": "Cargo Transport"},
    {"symbol": "BLUEDART",     "name": "Blue Dart Express Ltd",             "sector": "Logistics", "industry": "Express Delivery"},
    {"symbol": "TATACOMM",     "name": "Tata Communications Ltd",           "sector": "Telecom", "industry": "Telecom Services"},
    {"symbol": "TATAINVEST",   "name": "Tata Investment Corporation Ltd",   "sector": "Financial Services", "industry": "Holding Company"},
    {"symbol": "IPCALAB",      "name": "IPCA Laboratories Ltd",             "sector": "Pharmaceuticals", "industry": "Pharma"},
    {"symbol": "ISEC",         "name": "ICICI Securities Ltd",              "sector": "Financial Services", "industry": "Brokerage"},
    {"symbol": "MOTILALOFS",   "name": "Motilal Oswal Financial Services",  "sector": "Financial Services", "industry": "Brokerage"},
    {"symbol": "IIFL",         "name": "IIFL Finance Ltd",                  "sector": "Financial Services", "industry": "NBFC"},
    {"symbol": "FSL",          "name": "Firstsource Solutions Ltd",         "sector": "IT", "industry": "BPO"},
    {"symbol": "MINDTREE",     "name": "LTIMindtree Ltd",                   "sector": "IT", "industry": "IT Services"},
    {"symbol": "GLAND",        "name": "Gland Pharma Ltd",                  "sector": "Pharmaceuticals", "industry": "Pharma"},
    {"symbol": "GMRAIRPORT",   "name": "GMR Airports Infrastructure Ltd",   "sector": "Infrastructure", "industry": "Airports"},
    {"symbol": "IRB",          "name": "IRB Infrastructure Developers Ltd", "sector": "Infrastructure", "industry": "Roads"},
    {"symbol": "CENTRALBK",    "name": "Central Bank of India",             "sector": "Banking", "industry": "Public Bank"},
    {"symbol": "ABCAPITAL",    "name": "Aditya Birla Capital Ltd",          "sector": "Financial Services", "industry": "NBFC"},
    {"symbol": "BAJAJHLDNG",   "name": "Bajaj Holdings & Investment Ltd",   "sector": "Financial Services", "industry": "Holding Company"},
    {"symbol": "IEX",          "name": "Indian Energy Exchange Ltd",        "sector": "Energy", "industry": "Power Exchange"},
    {"symbol": "TRIDENT",      "name": "Trident Ltd",                       "sector": "Textiles", "industry": "Textiles"},
    {"symbol": "RAYMOND",      "name": "Raymond Ltd",                       "sector": "Textiles", "industry": "Textiles"},
    {"symbol": "ARVIND",       "name": "Arvind Ltd",                        "sector": "Textiles", "industry": "Textiles"},
    {"symbol": "KPRMILL",      "name": "KPR Mill Ltd",                      "sector": "Textiles", "industry": "Textiles"},
    {"symbol": "SAPPHIRE",     "name": "Sapphire Foods India Ltd",          "sector": "FMCG", "industry": "Quick Service Restaurant"},
    {"symbol": "WHIRLPOOL",    "name": "Whirlpool Of India Ltd",            "sector": "Consumer Durables", "industry": "Home Appliances"},
    {"symbol": "BLUESTARLT",   "name": "Blue Star Ltd",                     "sector": "Consumer Durables", "industry": "Air Conditioning"},
    {"symbol": "SYMPHONY",     "name": "Symphony Ltd",                      "sector": "Consumer Durables", "industry": "Air Cooling"},
    {"symbol": "RELAXO",       "name": "Relaxo Footwears Ltd",              "sector": "Consumer Goods", "industry": "Footwear"},
    {"symbol": "BATAINDIA",    "name": "Bata India Ltd",                    "sector": "Consumer Goods", "industry": "Footwear"},
    {"symbol": "CAMPUS",       "name": "Campus Activewear Ltd",             "sector": "Consumer Goods", "industry": "Footwear"},
    {"symbol": "PIXTRANS",     "name": "Pix Transmissions Ltd",             "sector": "Capital Goods", "industry": "Power Transmission"},
    {"symbol": "INDIANHUME",   "name": "Indian Hume Pipe Company Ltd",      "sector": "Infrastructure", "industry": "Pipes"},
    {"symbol": "SUPRAJIT",     "name": "Suprajit Engineering Ltd",          "sector": "Automobile", "industry": "Auto Components"},
    {"symbol": "AIAENG",       "name": "AIA Engineering Ltd",               "sector": "Capital Goods", "industry": "Castings"},
    {"symbol": "JYOTHYLAB",    "name": "Jyothy Labs Ltd",                   "sector": "FMCG", "industry": "Home Care"},
    {"symbol": "CASTROLIND",   "name": "Castrol India Ltd",                 "sector": "Energy", "industry": "Lubricants"},
    {"symbol": "GSPL",         "name": "Gujarat State Petronet Ltd",        "sector": "Energy", "industry": "Gas Transmission"},
    {"symbol": "POWERINDIA",   "name": "Hitachi Energy India Ltd",          "sector": "Capital Goods", "industry": "Electrical Equipment"},
    {"symbol": "SCHNEIDER",    "name": "Schneider Electric Infrastructure", "sector": "Capital Goods", "industry": "Electrical Equipment"},
    {"symbol": "SUMIT",        "name": "Summit Securities Ltd",             "sector": "Financial Services", "industry": "Holding Company"},
    {"symbol": "AFFLE",        "name": "Affle (India) Ltd",                 "sector": "Information Technology", "industry": "AdTech"},
    {"symbol": "TANLA",        "name": "Tanla Platforms Ltd",               "sector": "Information Technology", "industry": "Cloud Communications"},
    {"symbol": "INTELLECT",    "name": "Intellect Design Arena Ltd",        "sector": "Information Technology", "industry": "Fintech"},
    {"symbol": "ZENSARTECH",   "name": "Zensar Technologies Ltd",           "sector": "Information Technology", "industry": "IT Services"},
    {"symbol": "ECLERX",       "name": "eClerx Services Ltd",               "sector": "Information Technology", "industry": "BPO"},
    {"symbol": "TATATECH",     "name": "Tata Technologies Ltd",             "sector": "Information Technology", "industry": "Engineering Services"},
    {"symbol": "CMSINFO",      "name": "CMS Info Systems Ltd",              "sector": "Financial Services", "industry": "Cash Management"},
    {"symbol": "FIVESTAR",     "name": "Five-Star Business Finance Ltd",    "sector": "Financial Services", "industry": "NBFC"},
    {"symbol": "MAPMYINDIA",   "name": "C.E. Info Systems Ltd",             "sector": "Information Technology", "industry": "GIS & Mapping"},
    {"symbol": "HONASA",       "name": "Honasa Consumer Ltd (MamaEarth)",   "sector": "FMCG", "industry": "Personal Care"},
    {"symbol": "SWIGGY",       "name": "Swiggy Ltd",                        "sector": "Internet", "industry": "Food Delivery"},
    {"symbol": "AADHAAR",      "name": "Aadhaar Housing Finance Ltd",       "sector": "Financial Services", "industry": "Housing Finance"},
    {"symbol": "DATAPATTNS",   "name": "Data Patterns (India) Ltd",         "sector": "Defence", "industry": "Defence Electronics"},
    {"symbol": "SYRMA",        "name": "Syrma SGS Technology Ltd",          "sector": "Capital Goods", "industry": "Electronics Manufacturing"},
    {"symbol": "NETWEB",       "name": "Netweb Technologies India Ltd",     "sector": "Information Technology", "industry": "IT Hardware"},
    {"symbol": "JSWINFRA",     "name": "JSW Infrastructure Ltd",            "sector": "Infrastructure", "industry": "Ports"},
    {"symbol": "CELLO",        "name": "Cello World Ltd",                   "sector": "Consumer Goods", "industry": "Household Products"},
    {"symbol": "CONCORDBIO",   "name": "Concord Biotech Ltd",               "sector": "Pharmaceuticals", "industry": "API"},
    {"symbol": "SBFC",         "name": "SBFC Finance Ltd",                  "sector": "Financial Services", "industry": "NBFC"},
    {"symbol": "RBA",          "name": "Restaurant Brands Asia Ltd",        "sector": "FMCG", "industry": "Quick Service Restaurant"},
]

def main():
    # Deduplicate by symbol
    seen = set()
    unique = []
    for c in COMPANIES:
        sym = c["symbol"].upper()
        if sym not in seen:
            seen.add(sym)
            unique.append({
                "symbol": sym,
                "company_name": c["name"],
                "sector": c["sector"],
                "industry": c["industry"],
                "exchange": "NSE",
            })

    out_path = os.path.join(os.path.dirname(__file__), "data", "nifty500_companies.json")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(unique, f, indent=2, ensure_ascii=False)

    print(f"Generated {len(unique)} companies -> {out_path}")


if __name__ == "__main__":
    main()
